#Gems
gems:
    - jekyll-maps

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nottinghamshire Scouts Adventure
tagline:          'Fun | Friendship | Opportunity'
description:      ''
url:              http://www.nottsscoutsadventure.org.uk
baseurl:          /

author:
  name:           'Nottinghamshire Scouts'
  url:            https://twitter.com/NottsScouts

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nottsa

# Maps

maps:
    google:
      api_key: AIzaSyDA-HS8ju4jXSkzHIKKPkJ85ZJMGfa5m_g